#!/usr/bin/env sh
# Compatibility alias: `ros-hub` is the pre-rename name of `praxis-hub`
# (DF-ROS-2026-A050). New instructions use ./praxis-hub.
exec "$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)/praxis-hub" "$@"
